name: gen
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  very_good_analysis: ^9.0.0

  build_runner: ^2.5.4
  flutter_gen_runner: ^5.10.0
  easy_localization: ^3.0.7+1
  envied_generator: ^1.1.1
  json_serializable: ^6.9.5

flutter_gen:
  output: lib/src/asset/
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

    #fonts:
    #  - family: Raleway
    #    fonts:
    #      - asset: assets/fonts/Raleway-Regular.ttf
    #      - asset: assets/fonts/Raleway-Italic.ttf
    #        style: italic

