name: perceptron_delta_lab
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core Dependencies
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1

  # Localization
  easy_localization: ^3.0.7+1

  # Router
  go_router: ^16.0.0

  # Utilities
  logger: ^2.6.0
  linear_progress_bar: ^1.2.0

  # code gen
  gen:
    path: module/gen
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  very_good_analysis: ^9.0.0

  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/langs/
    - assets/icon/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
